<main>

<?php if(isAdmin()):?> <!--On sécurise la table-->

<table>
    <tr>
        <th>Client</th>
        <th>Date</th>
        <th>Heure</th>
        <th>Nombre de couverts</th>
    </tr>
    
    <?php foreach ($resalist as $resa) :?>
    <tr>
        <td><?= $resa['nom']?><?= $resa['prenom']?></td>
        <td><?= substr($resa['date'],0,10); ?></td>
        <td><?= substr($resa['date'],11); ?></td>
        <td><?= $resa['nb_couverts'] ?></td>
    </tr>            
                <?php endforeach; ?>
    
</table>
<?php else :?>

<?php
header('Location:index.php');
?>

<?php endif; ?>

</main>