    <main>
    <form action="index.php?action=connexion" method="post">
        <fieldset>
                <legend><i class="fas fa-lock"></i> Se connecter avec un compte utilisateur</legend>  
                <br>
                E-mail  <input name="email" type="email"><br><br>
                Mot de passe <input name="password" type="password"><br><br>
                <button id="submit" type="submit">Connexion</button>
                <button id="cancel">Annuler</button>
        </fieldset>
    </form>
</main>
